[project]
name = "iowa-housing-fastapi"
version = "0.1.0"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi[standard]==0.141.1",
    "scikit-learn==1.8.0",
    "pandas",
    "joblib",
    "python-dotenv",
    "databricks-sql-connector",
]

[tool.setuptools]
py-modules = ["main"]
packages = []

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"